### PR TITLE
Async task created. Fix stuff in tesouro cursor adapter.

### LINKED ISSUE #107: Create base async task to fetch tesouro data.

### LINKED ISSUE #108: Parse tesouro data from html.

### PR DESCRIPTION
**Pull request by DanMargera**
This pr closes #107 and includes @tabocu parse work that closes #108

### CODE REVIEW

File: app/src/main/java/sistemas/puc/com/finantialapp/FetchTesouroTask.java [hunk 1]
```diff
@@ -0,0 +1,149 @@
...
+
+        return null;
+    }
+
+    @Override
+    protected void onProgressUpdate(Void... voids) {}
+
+    @Override
+    protected void onPostExecute(List<ContentValues> result) {
+        if (result.size() > 0) {
```
Comment (tabocu) [inline app/src/main/java/sistemas/puc/com/finantialapp/FetchTesouroTask.java]: Check if result is null

File: app/src/main/java/sistemas/puc/com/finantialapp/FetchTesouroTask.java [hunk 2]
```diff
@@ -0,0 +1,149 @@
...
+                    (FinantialContract.TesouroEntry.CONTENT_URI, cvArray);
+        }
+    }
+
+    private List<ContentValues> getTesouroFromString(String tesouroString) throws Exception {
+        // Begin
+        HashMap<String, LinkedList<String>> tesouroHash = new HashMap<>();
+
+        Pattern vendaPatern = Pattern.compile("<tr class=\"camposTesouroDireto\">(.+?)</tr>");
+        Pattern compraPatern = Pattern.compile("<tr class=\"camposTesouroDireto \">(.+?)</tr>");
```
Comment (tabocu) [inline app/src/main/java/sistemas/puc/com/finantialapp/FetchTesouroTask.java]: Stract that to const

**Review by tabocu — APPROVED** [review]
Change that and merge

**Review by tabocu — APPROVED** [review]
